// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu5pbJ_w_1ZBHBgU4z2LJR7njzSJ5ATQg',
    appId: '1:747924766622:web:deaacf8212573c5dc0208f',
    messagingSenderId: '747924766622',
    projectId: 'moviable-xetz-app',
    authDomain: 'moviable-xetz-app.firebaseapp.com',
    storageBucket: 'moviable-xetz-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO7MrbQN7pZI7J4sznJLg2FGAIzfo9k4M',
    appId: '1:747924766622:android:bfa6c0d24e99a23fc0208f',
    messagingSenderId: '747924766622',
    projectId: 'moviable-xetz-app',
    storageBucket: 'moviable-xetz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1QvTiacqd9z_vGOyrH5uEDR0ybVudYnI',
    appId: '1:747924766622:ios:357921f9ecf401a2c0208f',
    messagingSenderId: '747924766622',
    projectId: 'moviable-xetz-app',
    storageBucket: 'moviable-xetz-app.appspot.com',
    iosClientId: '747924766622-evo8gu9o8fj32h11mkujc4h2bijfepem.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviable',
  );
}
